added html, css, and readme files and also added img folder with ima…
akinmolaomotlani/Portfolio-setup-and-mobile-first pull request #1
Opened 2023-04-27 18:04 UTC by akinmolaomotlani

1) Added HTML, CSS, and readme files 
2) Added image folder and images. 
3) installed linters HTML and CSS for the working environment.

2023-04-27 19:54 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @akinmolaomotlani  :wave: 

Well done!!! 👍 
You need to fix those issues before moving to the next project. :running_man: 

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Linters checks are passing.
✔️ You have used the correct git-flow.

## Required Changes ♻️

> Kindly check the comments below.

## Optional suggestions 🤷‍♂️

- [ ] ***[Optional]*** Kindly use capital letter as the first letter of a commit message as it is professional.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 19:54 UTC, Tufahel commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] Kindly remove this unnecessary line from the readme file. It looks unprofessional.

2023-04-27 19:54 UTC, Tufahel commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Kindly remove this unnecessary line from the readme file. It looks unprofessional.

2023-04-27 19:54 UTC, Tufahel commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ] Kindly remove this unnecessary line from the readme file. It looks unprofessional.

2023-04-27 19:54 UTC, Tufahel commented on README.md
> +> Write a message to encourage readers to support your project
- [ ] Kindly remove this unnecessary line from the readme file. It looks unprofessional.

2023-04-27 19:54 UTC, Tufahel commented on index.html
> +          </ul>
- [ ] Kindly use the given `icons` in the given [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39-122). 
- [ ] I can see you missed one icon given in the design template. Kindly use all the icons same as the given template to match the design.
- ***Your Design***
- ![image](https://user-images.githubusercontent.com/60083437/234970669-0c8e1d3c-deba-4590-8844-5e59cbfdc705.png)
- ***Given Design***
- ![image](https://user-images.githubusercontent.com/60083437/234970521-6537bc95-1546-458a-9ff7-6ec1be7e4f8b.png)

2023-04-27 19:54 UTC, Tufahel commented on index.html
> +        <a class="connect-link" href="#">LET'S CONNECT</a>
- [ ] Kindly use the correct font for `LET'S CONNECT` to match the given design.
- ***Your Design***
- ![image](https://user-images.githubusercontent.com/60083437/234971136-b69f5ff7-18bb-4ead-a636-4e89998f2131.png)
- ***Given Design***
- ![image](https://user-images.githubusercontent.com/60083437/234971503-8fc07bed-dad2-4773-a1ee-da649582c62f.png)

2023-04-27 19:54 UTC, Tufahel commented on index.html
> +        <h1 class="heading-primary">I’m Omotolani. Glad to see you!</h1>
- From the given design I can see there are more `gaps` between each line of the `Title`.
- ***Given Design***
- ![image](https://user-images.githubusercontent.com/60083437/234973453-c3ced257-eec5-438b-ba97-3cf7e5b782d0.png)
- But in your design, I can't see any `gaps` between each line.
- ***Your Design***
- ![image](https://user-images.githubusercontent.com/60083437/234974394-b8350e37-264d-4ddf-90ea-9840de6f1651.png)

- [ ] Kindly fix the issue to match the given design.

2023-04-27 19:54 UTC, Tufahel commented on index.html
> +          </ul>
- [ ] You have used `ul` but haven't used `li` to list the `nav` items. Kindly fix this issue to be semantically correct. You can consider the following suggestion.

`<ul>`
`<li><a></a></li>`
`<li><a></a></li>`
`</ul>`

2023-04-28 07:12 UTC, TadesseDev requested changes
### Hi @akinmolaomotlani 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 07:12 UTC, TadesseDev commented on README.md
- [ ] Also here, the previous reviewer has mentioned adding a description of how to install this website on anyone's PC. I notice You have removed this section. Please remember all the headings from the readme template should be present and customized. Hence I should suggest adding this section back and adding an instruction on how to install this project.

2023-04-28 07:12 UTC, TadesseDev commented on index.html
> +      <div class="header">
- [ ] Good job Updating the initial design for a 375px screen size, But while doing so I notice your background image is not aligned properly, Please follow the design guideline and try to design something identical to the Figma design. 
- [Optional] Please use a header tag for your `Toolbar` section,  Typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.
- [Optional] Please also notice that you don't need two headers on your page, The first header is part of the mobile where your webpage will be opened and should not be part of the webpage, Please consider removing it.  
### Your design 
![image](https://user-images.githubusercontent.com/69077061/235078099-53c099e0-28f2-4201-b5fe-56bd76d3f1be.png)
### Expected figma design 
![image](https://user-images.githubusercontent.com/69077061/235078824-d3c598c1-6f75-4ada-84d2-a53ebad8a424.png)

2023-04-28 07:12 UTC, TadesseDev commented on index.html
> +                ><i class="fa-brands fa-angellist"></i
- [ ] Dear @akinmolaomotlani, as mentioned by the previous reviewer, We need to use the provided icons in the design to make our webpage identical to the one provided. 

### Icons in your webpage 
![image](https://user-images.githubusercontent.com/69077061/235079290-ced64800-1d35-4f1a-bf9b-37a60b98b157.png)

### Icons from the figma design 
![image](https://user-images.githubusercontent.com/69077061/235079224-9411652e-4214-408c-a51a-cc6c10e2931a.png)

2023-04-28 13:49 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @akinmolaomotlani 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 13:49 UTC, anagudelogu commented on README.md
> + -->
- [ ] As suggested by the previous reviewer, please modify the "Getting Started" Section of your README file. This is because is one of the most important sections of your documentation as it lets other people wanting to collaborate on your project know how they can easily get a local copy up and running.

I suggest that at least you add the instructions to Setup (Cloning the repo), Install (Install project dependencies), and Usage (Open with live server). This will serve as a basic quick-start guide. Once you have these sections, it is safe to remove the commented code to keep it clean! 🤓 🔧

2023-04-28 13:49 UTC, anagudelogu commented on index.html
> +              ></a>
- [ ] As suggested by the previous reviewer, there are still some issues with the background image not showing correctly:

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/235163655-fc78f24e-5bb1-46b5-9aeb-cd6986828632.png) | ![image](https://user-images.githubusercontent.com/77069011/235163494-8862fb8c-b02a-4780-bfc2-1b7e5dccfdb6.png) |

This is because you have the property `background-size: cover` in your CSS, if you remove it, the background would fit as expected! 🤓 🔧

2023-04-28 13:49 UTC, anagudelogu commented on index.html
> +        </nav>
- [ ] Also, as the previous reviewer suggested, please consider using the same icons that the FIGMA design provides, this is because one of the main goals of this project is to demonstrate your ability to follow as closely as possible a given design! Consider changing them! 🤓 🔧 

💡 To download an icon from FIGMA just click on the icon:

![image](https://user-images.githubusercontent.com/77069011/235165090-4475f23b-fb18-4c4f-85d6-ccdb331a6713.png)

Then, in the right panel click on the "Export" tab:

![image](https://user-images.githubusercontent.com/77069011/235165300-3d031003-3397-49e2-8621-17f11f261b70.png)

Finally, Select the desired format and click on the "Export" button:

![image](https://user-images.githubusercontent.com/77069011/235165491-77c3c636-9746-45bb-878a-cdd3fc163524.png)

2023-04-28 17:12 UTC, divinecharlotte requested changes
Hi @akinmolaomotlani    , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- linters are passing 👍
- descriptive pr 👍 





 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️



_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 17:12 UTC, divinecharlotte commented on README.md
> +3. and Usage (Open with live server).
- [ ] Kindly as requested by the previous reviewer consider  making this section more descriptive by being specific on which link to use when cloning, which branch to access your work from

2023-04-28 17:12 UTC, divinecharlotte commented on index.html
> +    </section>
- [ ] kindly consider giving this section some padding top and bottom for it to look exactly as the one given in the Figma design check the images below to see what to improve 
- your design 👇 
<img width="368" alt="Screen Shot 2023-04-28 at 19 09 16" src="https://user-images.githubusercontent.com/60146030/235210942-ccda3473-99b5-4485-ab0b-ecb3fa12ab68.png">
 

-Figma design 👇 
<img width="344" alt="Screen Shot 2023-04-28 at 19 10 08" src="https://user-images.githubusercontent.com/60146030/235211077-3e9e16ea-89d3-4a96-a561-091ede197802.png">

2023-04-28 17:17 UTC, akinmolaomotlani commented on index.html
> +    </section>
I am not happy at all. you are writing different comments entirely. I am confused. bringing different issues to every review. what is going on?

2023-04-28 19:22 UTC, IngDavidTM approved these changes
Hi @akinmolaomotlani 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

- [OPTIONAL] Please take into consideration matching the color of the hamburger button to #6070FF, which is consistent with the Figma template :+1:. By doing so, the button will blend in more seamlessly with the overall design of the website and create a more cohesive look. This attention to detail will also showcase a level of professionalism and attention to design that will positively impact the user's perception of your website.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 16:44 UTC, merged