Contact section
akinmolaomotlani/Portfolio-setup-and-mobile-first pull request #4
Opened 2023-05-09 12:57 UTC by akinmolaomotlani

1. Added html and css files to the project 
2. installed the html,css linters

2023-05-09 15:49 UTC, Abenezer-Tilahun requested changes
Hi @akinmolaomotlani @tajulafreen   , 

Great job for implemented  the some of the Project Requirement , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linter errors
✔️ Good commit messages
✔️ Professional README

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [ ]  As stated in the project requirement Kindly make sure that each card on the board has the **number of points in the [Xpt**] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work.
a description of the task and **Has a description of the task.**

![Capture](https://user-images.githubusercontent.com/93598189/237057350-f1816cb5-5b98-4968-abe9-1c14b9cdfc46.PNG)

![Capture](https://user-images.githubusercontent.com/93598189/237057604-be45fae5-de1f-468a-86f1-c93c8ead0d92.PNG)

- [ ] But in the case of yours Kanban board there is no he **number of points in the [Xpt**] prefix on all of your cards and some of your cards has no  **a description of the task.** Just Like the following cards, So Kindly Fix it before resubmit for review.

![Capture](https://user-images.githubusercontent.com/93598189/237058453-5713ca26-c7a1-4c11-8236-cdf531ddfe9f.PNG)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 15:49 UTC, Abenezer-Tilahun commented on index.html
> +    <button class="btn send" type="button">Send</button>
- [ ] Kindly I recommend you to include the button inside the form to submit the form successfully and as stated in the project requirement Kindly Button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template.
![Capture](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/93598189/7a505d8f-12f4-4cec-92d5-b1ced3bf7bbb)

2023-05-10 02:57 UTC, Shedrack-Sunday requested changes
Hello @akinmolaomotlani       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use implementation of  a couple of highlighted changes ✔️    

  
# Required Changes  🌵 

- [x] You made some impressive efforts as regards the previous review suggestion of  which I must say is a job well done. However, there's one you missed 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-10 02:57 UTC, Shedrack-Sunday commented on index.html
> +            <div>
- [ ] As highlighted by the previous reviewer, kindly replace the `{form_id}` with the form in your [formspree account](https://formspree.io/html/) so your form can be successfully submitted. The link highlighted has a detailed approach to that.
- I'll advice you make sure it submits before sending for another review 👍

2023-05-10 02:57 UTC, Shedrack-Sunday commented on index.html
> +                required
- [ ] As rightly suggested by the last reviewer, kindly add validations on this name input field a length of `30` as specified on the project requirements. 
- This makes sure the input from the user is very reasonable 👍 

## Requirements:
![image](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/50990925/eb10fe84-bf51-4407-be47-e8c07a934138)

2023-05-10 02:57 UTC, Shedrack-Sunday commented on style.css
> +  text-align: center;
- [ ] Nice job using Flexbox as rightly stated by the last reviewer 👏 . However, you still need to adjust the startin point of the input in the text area in the form. From the comparison below, you can see they are clearly not the same as given in the Figma design.
- In the `button`

## Figma:
![image](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/50990925/4b00b989-1225-4167-a4e8-996e2fc3c334)

## Your design:
![image](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/50990925/1939192a-b07d-4ceb-a1f3-2f6ff3d38f11)

2023-05-10 06:51 UTC, Efiamotu-1 approved these changes
Hi @akinmolaomotlani , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 06:51 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [ ] please i kindly suggest that you apply the appropriate border-radius your design for each input and textareas as shown in the figma template below. It is important that your design matches closely the figma template as it shows how much attention to details you pay as a developer :+1:  :sparkles: 
- [ ] Also work on improving the fonts of the placeholder text as well as theit color see the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&t=kCqJowj7ub2IRXn2-0) for this. :+1: 
- figma design
![f-f](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/89055502/84af3b00-d38f-418b-aad7-fe24e07824b4)
- your design
![f-s](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/89055502/eae2db5f-3533-4e45-ae22-9fc206ace6ff)

2023-05-10 10:11 UTC, merged