added media query file, modified html css
akinmolaomotlani/Portfolio-setup-and-mobile-first pull request #5
Opened 2023-05-11 15:00 UTC by akinmolaomotlani

1. Added Media query file to build a responsive portfolio.
2. Modified the HTML, and CSS files 
3. installed linters for HTML and CSS.

2023-05-11 17:12 UTC, taldr27 requested changes
# Status: Required Changes ♻️♻️
Hello @akinmolaomotlani, 

Good job so far! 
You're making good progress on the project, but some issues still need to be addressed before you can move on to the next stage. Keep up the good work! 💪

![almost-there](https://media.giphy.com/media/l1JojjVanlckKIHMQ/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Nice job adding some of your media queries.

## Required Changes ♻️
_Check the comments under the review._

------
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-11 17:12 UTC, taldr27 commented on index.html
>              what you see and have a project you need coded, don’t hesitate to
- [ ] Great job on your portfolio! However, I noticed that your `About section` is not looking like the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&t=4iZSZXlT6CNqqnEX-0) provided. To make it closer to the template, I suggest **giving the left element 40% and the right element 60% of the page's `width`**. Additionally, adding s**ome space and `padding` between them** can also make it look better. Keep up the good work! 💪

  ### Your design:
  ![image](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/107952724/a448710e-2739-47c4-b32b-1207a3a9adb5)

  ### Figma design:
  ![image](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/107952724/8b88cf36-8dcd-4ff1-9287-2627a47eb96b)

2023-05-11 17:12 UTC, taldr27 commented on index.html
>        </div>
Great job on your contact section! Here are a couple of suggestions to make it even better and more closely match the Figma design:

- [ ] Please double-check that you are using the correct `background image` for your contact section, as it does not appear to be displaying correctly. 🎯
- [ ] Additionally, please review the size of your `Get in touch` button, as it does not match the size of the button in the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&t=4iZSZXlT6CNqqnEX-0) provided. 🙌

  ### Your design:
  ![image](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/107952724/5e441e9c-bde6-435b-bc79-384945c0c943)

  ### Figma design:
  ![image](https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/107952724/5a56bb4a-9337-4ddf-9df8-d20b2129e1e4)

2023-05-12 13:24 UTC, Strangeal requested changes
Hi @akinmolaomotlani, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 13:24 UTC, Strangeal commented on index.html
>        </div>
- [ ] The previous reviewer suggested that it implement the `background-image` properly not remove it. This will make your design look beautiful and create a good user experience. Please adhere to the requirements of the previous reviewer.  Thank you😊

2023-05-12 13:24 UTC, Strangeal commented on style.css
- `[OPTIONAL]` Kindly consider adding a `:hover` effect on your buttons to match that of the `Figma` design template. This will make your design stand out and create a good user experience. See below for more details:
<table>
<tr>
<th align=“middle”>Figma design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="754" alt="Screenshot 2023-05-12 at 13 22 32" src="https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/107192076/4ac3448c-3353-451e-b0ef-9092f3d151be">
</td>
<td>
<img width="168" alt="Screenshot 2023-05-12 at 13 21 29" src="https://github.com/akinmolaomotlani/Portfolio-setup-and-mobile-first/assets/107192076/847b8c84-6a4e-4016-aa60-603c621c3f26">
</td>
</tr>
</table>

2023-05-12 14:32 UTC, akinmolaomotlani commented on style.css
I will be adding that in the transition and animation section

2023-05-12 15:37 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @akinmolaomotlani,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-05-12 17:00 UTC, merged